
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer

import subprocess
from pathlib import Path
import sys
from tkinter import *

from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage, Label
import mysql.connector
import subprocess

global username
username = sys.argv[1] if len(sys.argv) > 1 else "User"


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\hicha\OneDrive\Desktop\DBMSSSS\DBMS_Project_code\build\assets\frame0")

conn = mysql.connector.connect(
            host="localhost",
            user="root",
            password="riya2004",
            database="health_fitness"
        )
cursor = conn.cursor()

def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

def open_file_with_delay(filename,username, delay=2000):
    subprocess.Popen(['python', rf'C:\Users\hicha\OneDrive\Desktop\DBMSSSS\DBMS_Project_code\{filename}',username])
    window.after(delay, window.destroy)

def open_del(filename,username, delay=8000):
    subprocess.Popen(['python', rf'C:\Users\hicha\OneDrive\Desktop\DBMSSSS\DBMS_Project_code\{filename}',username])
    window.after(delay, window.destroy)

def meal_type_changed(meal_type):
    
    fetch_nutrition_plan(meal_type)


def fetch_nutrition_plan(meal_type):
    
    conn = mysql.connector.connect(
        host="localhost",
        user="root",
        password="riya2004",
        database="health_fitness"
    )
    
    cursor = conn.cursor()
    
   
   
    cursor.execute("SELECT MEALTIME,MEALTYPE,CALORIECOUNT,DESCRIPTION FROM NUTRITIONPLANS WHERE MEALTYPE=%s", (meal_type,))
    
    
    results = cursor.fetchall()
    
    
    result_str = "-" * 135 + "\n"
    result_str += "MEALTIME  | MEALTYPE\t| CALORIE COUNT\t| DESCRIPTION\n"
    result_str += "-" * 135 + "\n"
    
    for row in results:
        
        if row[0]=="Breakfast":
            if row[1]=="Low Carb" or  row[1]=="High Protein" or  row[1]=="Weight Loss":
                result_str += f"{row[0]}    | {row[1]}\t| {row[2]}\t\t| {row[3]}\n"
            else:
                result_str += f"{row[0]}    | {row[1]}\t\t| {row[2]}\t\t| {row[3]}\n"
        else:
            if row[1]=="Low Carb" or  row[1]=="High Protein" or  row[1]=="Weight Loss":
                result_str += f"{row[0]}\t   | {row[1]}\t| {row[2]}\t\t| {row[3]}\n"
            else:
                result_str += f"{row[0]}\t   | {row[1]}\t\t| {row[2]}\t\t| {row[3]}\n"
    result_str += "-" * 135 + "\n"
    canvas.delete("result_label")  
    
    
    canvas.create_text(
        470, 535, 
        text=result_str, 
        font=("Otomanopee One", 11), 
        fill="#84A928", 
        anchor="nw", 
        tags="result_label"  
    )
    
    # Close the connection
    cursor.close()
    conn.close()

window = Tk()

window.geometry("1536x806+0+0")
window.configure(bg = "#84A928")


canvas = Canvas(
    window,
    bg = "#84A928",
    height = 806,
    width = 1536,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    768.0,
    512.0,
    image=image_image_1
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    768.0,
    512.0,
    image=image_image_2
)

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    944.0,
    509.0,
    image=image_image_3
)

image_image_4 = PhotoImage(
    file=relative_to_assets("image_4.png"))
image_4 = canvas.create_image(
    745.0,
    103.0,
    image=image_image_4
)

canvas.create_text(
    447.0,
    58.0,
    anchor="nw",
    text="NUTRITION PLAN",
    fill="#FFB001",
    font=("Otomanopee One", 64 * -1)
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: open_file_with_delay("Nutrition_logs.py",username),
    relief="flat"
)
button_1.place(
    x=1116.0,
    y=27.0,
    width=379.0,
    height=152.0
)
canvas.create_text(
    474.0,
    326.0,
    anchor="nw",
    text="Meal type",
    fill="#84A928",
    font=("Otomanopee One", 36 * -1)
)


meal_types = ["Veg", "Vegan", "High Protein", "Keto", "Low Carb", "Weight Loss"]
meal_type_var = StringVar()
meal_type_var.set("Choose Meal") 


meal_type_menu = OptionMenu(window, meal_type_var, *meal_types)


meal_type_menu.config(font=("Otomanopee One", 20), fg="#84A928", bg="#CAE2CC")  


meal_type_menu["menu"].config(font=("Otomanopee One", 20), fg="#84A928", bg="#CAE2CC") 


meal_type_menu.place(x=744.0, y=315.0, width=662.0, height=65.0)


meal_type_var.trace("w", lambda *args: meal_type_changed(meal_type_var.get()))


image_image_5 = PhotoImage(
    file=relative_to_assets("image_5.png"))
image_5 = canvas.create_image(
    941.0,
    584.0,
    image=image_image_5
)


canvas.create_text(
    490.0,
    455.0,
    anchor="nw",
    text="Your Meal Plan -",
    fill="#FFB001",
    font=("Otomanopee One", 36 * -1)
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat",
    background="#3C98A4"
)
button_2.place(
    x=83.0,
    y=10.0,
    width=180.0,
    height=188.51348876953125
)

image_image_6 = PhotoImage(
    file=relative_to_assets("image_6.png"))
image_6 = canvas.create_image(
    176.0,
    505.0,
    image=image_image_6
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda:  open_file_with_delay("Health_metrics.py",username),
    relief="flat",
    background="#CAE2CC"
)
button_3.place(
    x=68.76922607421875,
    y=330.84423828125,
    width=214.46151733398438,
    height=72.76707458496094
)

button_image_4 = PhotoImage(
    file=relative_to_assets("button_4.png"))
button_4 = Button(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: open_file_with_delay("Goals_and_progress.py",username),
    relief="flat",
    background="#CAE2CC"
)
button_4.place(
    x=68.76922607421875,
    y=413.3134765625,
    width=214.46151733398438,
    height=72.76707458496094
)

button_image_5 = PhotoImage(
    file=relative_to_assets("button_5.png"))
button_5 = Button(
    image=button_image_5,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_5 clicked"),
    relief="flat",
    background="#CAE2CC"
)
button_5.place(
    x=68.76922607421875,
    y=586.984375,
    width=214.4615478515625,
    height=72.76707458496094
)

button_image_6 = PhotoImage(
    file=relative_to_assets("button_6.png"))
button_6 = Button(
    image=button_image_6,
    borderwidth=0,
    highlightthickness=0,
    command=lambda:open_file_with_delay("User_dashboard.py",username),
    relief="flat",
    background="#CAE2CC"
)
button_6.place(
    x=68.76922607421875,
    y=251.285400390625,
    width=214.46151733398438,
    height=72.76707458496094
)

button_image_7 = PhotoImage(
    file=relative_to_assets("button_7.png"))
button_7 = Button(
    image=button_image_7,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: open_file_with_delay("Workouts.py",username),
    relief="flat",
    background="#CAE2CC"
)
button_7.place(
    x=68.76922607421875,
    y=497.723388671875,
    width=214.46151733398438,
    height=72.76707458496094
)

button_image_8 = PhotoImage(
    file=relative_to_assets("button_8.png"))
button_8 = Button(
    image=button_image_8,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: open_file_with_delay("User_profile.py",username),
    relief="flat",
    background="#CAE2CC"
)
button_8.place(
    x=69.0,
    y=677.0,
    width=95.0,
    height=88.0
)

button_image_9 = PhotoImage(
    file=relative_to_assets("button_9.png"))
button_9 = Button(
    image=button_image_9,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: open_del("Delete_all.py",username),
    relief="flat",
    background="#CAE2CC"
)
button_9.place(
    x=176.0,
    y=677.0,
    width=95.0,
    height=88.0
)
window.resizable(True, True)
window.mainloop()
conn.commit()
cursor.close()
